export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const GET_ITEMS_CART = "GET_ITEMS_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
